name: MC-OmniSight
version: '1.0-SNAPSHOT'
main: org.lbynb.mCOmniSight.MCOmniSight
api-version: '1.19'
commands:
  placecamera:
    description: Place a camera at your location.
    usage: /placecamera <type>
  removecamera:
    description: Remove a camera you own.
    usage: /removecamera
  mass:
    description: Main command for MASS camera management.
    usage: /mass <create|manage> [arguments]
    permission: mass.admin
permissions:
  mass.admin:
    description: Allows use of all MASS camera commands
    default: op
